from __future__ import annotations

import json
from typing import Any, Dict, List

from data_utils import to_datetime, to_float
from deps import require_networkx
from ollama_client import OllamaClient


def build_lease_property_kg(
    lease_rows: List[Dict[str, str]],
    property_rows: List[Dict[str, str]],
) -> Any:
    """Create a knowledge graph that combines lease and property data."""
    nx = require_networkx()
    graph = nx.MultiDiGraph(name="lease_property_kg")

    properties_by_id: Dict[str, Dict[str, str]] = {
        row["property_id"]: row for row in property_rows
    }

    for row in property_rows:
        property_id = row["property_id"]
        property_node = f"property:{property_id}"

        graph.add_node(
            property_node,
            label="Property",
            property_id=property_id,
            usage_type=row.get("property_usage_type") or None,
            class_type=row.get("property_class") or None,
            address=row.get("address_line") or None,
            city=row.get("city") or None,
            state=row.get("state") or None,
            postal_code=row.get("postal_code") or None,
            net_rentable_area=to_float(row.get("net_rentable_area")),
            total_gross_area=to_float(row.get("total_gross_area")),
            last_sale_price=to_float(row.get("last_sale_price")),
        )

        city = row.get("city")
        if city:
            city_node = f"city:{city.lower()}"
            graph.add_node(city_node, label="City", name=city)
            graph.add_edge(property_node, city_node, relation="LOCATED_IN_CITY")

        state = row.get("state")
        if state:
            state_node = f"state:{state.lower()}"
            graph.add_node(state_node, label="State", code=state)
            graph.add_edge(property_node, state_node, relation="LOCATED_IN_STATE")

        market = row.get("market_name")
        if market:
            market_node = f"market:{market.lower()}"
            graph.add_node(market_node, label="Market", name=market)
            graph.add_edge(property_node, market_node, relation="IN_MARKET")

    for row in lease_rows:
        lease_id = row["lease_id"]
        lease_node = f"lease:{lease_id}"

        graph.add_node(
            lease_node,
            label="Lease",
            lease_id=lease_id,
            total_leased_space=to_float(row.get("total_leased_space")),
            asking_rent_monthly=to_float(row.get("asking_rent_monthly")),
            base_rent_monthly=to_float(row.get("base_rent_monthly")),
            start_date=to_datetime(row.get("start_date")),
            end_date=to_datetime(row.get("end_date")),
            signed_date=to_datetime(row.get("signed_date")),
            lease_status=row.get("lease_status") or None,
            lease_type=row.get("lease_type") or None,
            usage_type=row.get("property_usage_type") or None,
        )

        property_id = row.get("property_id")
        if not property_id:
            continue

        property_node = f"property:{property_id}"
        is_known_property = property_id in properties_by_id

        if not is_known_property:
            graph.add_node(
                property_node,
                label="Property",
                property_id=property_id,
                unresolved=True,
            )

        graph.add_edge(
            lease_node,
            property_node,
            relation="HAS_LEASED_PROPERTY",
            source="lease_data",
        )

        lease_usage = row.get("property_usage_type")
        if lease_usage:
            usage_node = f"usage:{lease_usage.lower()}"
            graph.add_node(usage_node, label="UsageType", name=lease_usage)
            graph.add_edge(lease_node, usage_node, relation="LEASE_USAGE")

        property_usage = properties_by_id.get(property_id, {}).get("property_usage_type")
        if property_usage:
            p_usage_node = f"usage:{property_usage.lower()}"
            graph.add_node(p_usage_node, label="UsageType", name=property_usage)
            graph.add_edge(property_node, p_usage_node, relation="PROPERTY_USAGE")

    return graph


def enrich_with_ollama_insights(graph: Any, ollama: OllamaClient) -> None:
    """Optionally add an Insight node generated by Ollama."""
    summary_payload = {
        "num_nodes": graph.number_of_nodes(),
        "num_edges": graph.number_of_edges(),
        "leases": [n for n, d in graph.nodes(data=True) if d.get("label") == "Lease"],
        "properties": [n for n, d in graph.nodes(data=True) if d.get("label") == "Property"],
    }

    prompt = (
        "Given this lease-property graph summary, provide up to 3 concise business insights "
        "as a JSON array of strings only.\n"
        f"Summary: {json.dumps(summary_payload)}"
    )

    response = ollama.generate(prompt)
    start = response.find("[")
    end = response.rfind("]")
    if start == -1 or end == -1 or end <= start:
        return

    try:
        insights = json.loads(response[start : end + 1])
    except json.JSONDecodeError:
        return

    if not isinstance(insights, list):
        return

    insight_hub = "insight:lease_property"
    graph.add_node(insight_hub, label="InsightCollection")
    for i, text in enumerate(insights, start=1):
        if not isinstance(text, str) or not text.strip():
            continue
        node_id = f"insight:{i}"
        graph.add_node(node_id, label="Insight", text=text.strip())
        graph.add_edge(insight_hub, node_id, relation="HAS_INSIGHT")


def print_graph_snapshot(graph: Any) -> None:
    """Print a compact snapshot of the graph."""
    print("\n=== Knowledge Graph Snapshot ===")
    print(f"Graph name: {graph.graph.get('name')}")
    print(f"Nodes: {graph.number_of_nodes()}")
    print(f"Edges: {graph.number_of_edges()}")

    print("\nNode samples:")
    for node, attrs in list(graph.nodes(data=True))[:8]:
        print(f"- {node}: {attrs}")

    print("\nEdge samples:")
    for source, target, attrs in list(graph.edges(data=True))[:10]:
        print(f"- {source} --[{attrs.get('relation')}]--> {target}")
